### The Zen of python

In [1]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


### Data Types

In python, declaration of variables is optional.

##### Integer
Integers are default initialised to 0.
https://docs.python.org/3/library/functions.html#int

In [2]:
a = 1   # integer
print ('Type:', type(a))
print ('a:', a)
b = int()
print ('b:', b)
b = 5
print ('b:', b)

Type: <class 'int'>
a: 1
b: 0
b: 5


##### Float
https://docs.python.org/3/library/functions.html#float

In [3]:
flt = 1.0 # Float
print ('Type:', type(flt))
print (flt)

Type: <class 'float'>
1.0


###### Boolean
Possible Values: True or False

In [1]:
x = 1
print (x == 1)
print (x == 2)
x = True
type(x)

True
False


bool

##### String

In [3]:
for i in range (0, 5):
    print(i);

0
1
2
3
4


In [5]:
strin = 'hello, world' #String
print ('Type:', type(strin))
print (strin)
print (strin[0:2], strin[:2], strin[-1]) # negetive indexing begins from back

Type: <class 'str'>
hello, world
he he d


##### List
List is like an array of C with many inbuilt functions like for insertion and deletion.
https://developers.google.com/edu/python/lists

https://docs.python.org/3/tutorial/datastructures.html

In [6]:
lst = [1, 2, 5] #list
print (lst, lst[:2])

lst.append(10)
print (lst)

lst.remove(5)
print (lst)

print ('Length of list:', len(lst))
print (lst[-1], lst[-2])    # lst[-x] represents lst[len(lst) - x]

[1, 2, 5] [1, 2]
[1, 2, 5, 10]
[1, 2, 10]
Length of list: 3
10 2


##### Dictionary
A dictionary object is like an original dictionary. Like in dictionary, every word has a meaning. Similarly, in dictionary object, every key has a value.

https://docs.python.org/3/tutorial/datastructures.html#dictionaries

In [7]:
dictt = {
    'apple': 1,
    'mango': 2
}
print (dictt)
print(dictt['apple'])
dictt['orange'] = 3
print(dictt)

{'apple': 1, 'mango': 2}
1
{'apple': 1, 'mango': 2, 'orange': 3}


###### Some more data structures:

Tuples: https://docs.python.org/3/tutorial/datastructures.html#tuples-and-sequences

Sets: https://docs.python.org/3/tutorial/datastructures.html#sets

### Taking input from user

###### input()
input always take strings as input.

In [8]:
x = input('Enter a number: ')
print (type(x), x)
y = int(x)                  #Type conversion from string to Integer
print (type(y), y)

Enter a number: 4
<class 'str'> 4
<class 'int'> 4


### Operators in python

In [9]:
x = 2
y = 3

print ('Addition: ', x+y)
print ('Subtraction: ', x-y)
print ('Multiplication: ', x*y)
print ('Exponentiation: ', x**y)          # x^y
print ('Division in floats: ', x/y)
print ('Division in ints: ', x//y)

z = 5
z += x                # Similar to z = z + x
print ('z: ', z)

Addition:  5
Subtraction:  -1
Multiplication:  6
Exponentiation:  8
Division in floats:  0.6666666666666666
Division in ints:  0
z:  7


### Control flow
https://docs.python.org/3/tutorial/controlflow.html

When you want to write a block statement, we use indentation. Same level of indentation represents sub-block.

##### If-else statements
if (condition):
    
    code

elif (condtion):          #elif similar to else if

    code
    
else:

    code

In [10]:
x = 5
y = 10
if x>y:
    print ('x is greater than y')
elif(y>x):
    print ('y is greater than x')
else:
    print ('x is equal to y')

y is greater than x


##### For loop

for i in range(initial_value, final_value):
    # i takes on different value for each iteration
    
for loops can also iterate over lists

lst = [1, 5, 10]

for i in lst:
    
    print (i)
    
output: 1 5 10

In [11]:
for i in range(0, 5):
    print (i)

0
1
2
3
4


In [14]:
lst = [1, 5, 10]
for i in lst:
    print (i)
    print("Hi")

1
Hi
5
Hi
10
Hi


###### While loops
https://docs.python.org/3/reference/compound_stmts.html#while

while (condition):
    #code

In [13]:
i=5
while(i>0):
    print (i)
    i -= 1            #similar to i = i-1

5
4
3
2
1


### Functions
https://docs.python.org/3/tutorial/controlflow.html#defining-functions

Functions in python can return one or multiple values

def function_name(argument1, arguments2):
    #code

In [14]:
def fun(x, y):
    a = x+y
    b = x*y
    return a, b

print (type(fun(2, 3)))
p, q = fun(2, 3)
print (p, q)

<class 'tuple'>
5 6


#### One last magic!
Swapping values in python

In [15]:
x = 2
y = 3
x, y = y, x
print (x)
print (y)

3
2


In [4]:
a = 1
b = 2
c = 3
a, b, c = b, c, a
print(a, b, c)

2 3 1


In [10]:
x = input("Enter a number: ");
print(type(x), x)
x = float(x)
print(type(x), x)

Enter a number: 6
<class 'str'> 6
<class 'float'> 6.0


1
10


In [3]:
x = 10000000
for i in range (1, 10):
    print(i)
    x = x**i
    print(i, type(x), x)

1
1 <class 'int'> 10000000
2
2 <class 'int'> 100000000000000
3
3 <class 'int'> 1000000000000000000000000000000000000000000
4
4 <class 'int'> 1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
5
5 <class 'int'> 10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

In [1]:
li = [1, 2, 3]
li1 = [1, 4, 5, 3, 6]
print(li + li1)

[1, 2, 3, 1, 4, 5, 3, 6]


In [6]:
empty_dict = {}
f_dict = {"one": 1, "two": 2, "three": 3}  #keys should be immutable...values can be mutable
print(f_dict.keys())
print(f_dict["one"])
#del f_dict["four"] 

dict_keys(['one', 'two', 'three'])
1


In [9]:
def add(x, y):
    return x, y, x + y

a, b, c = add(4, 5)
print(a, b, c)

4 5 9


In [11]:
a = 7
b = 10
print(a, b)
a, b = b, a
print(a, b)

7 10
10 7


In [13]:
import numpy as np
a = np.arange(15)
print(a)
a = a.reshape(3,5)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
